### ISSUE TITLE
链接进不去……

### ISSUE THREAD

**Issue by Redsparkfish** [YangYunCan/CAD-Models#1]
链接挂了，能补档吗，球球了

**Comment by YangYunCan** [comment]
> 链接挂了，能补档吗，球球了

我毕业交接给下面几届了，我帮你问问

**Comment by YangYunCan** [comment]
> 链接挂了，能补档吗，球球了

你有邮箱或者其他联系方式吗？

**Comment by YangYunCan** [comment]
> 链接挂了，能补档吗，球球了

可以留个邮箱或者其他联系方式吗？

**Comment by Redsparkfish** [comment]
670018291@qq.com

**Comment by Redsparkfish** [comment]
> > 链接挂了，能补档吗，球球了
> 
> 可以留个邮箱或者其他联系方式吗？

还在吗？
